language: python
sudo: true # old infrastructure
cache: pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - python-cairo

env:
  global:
  - VERSION="6.1" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get -qy update

install:
  - sudo apt-get -y install libreoffice
  - sudo apt-get -y install python-genshi
  - sudo apt-get -y install python-uno
  - sudo apt-get -y install python-openoffice
  - git clone https://github.com/aeroo/aeroolib
  - cd aeroolib && sudo python ./setup.py install
  - git clone --depth=1 https://github.com/open-synergy/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
